View
Delismachado/probable-journey pull request #6
Opened 2021-02-07 21:24 UTC by Delismachado

Category -> Api and Web
API:
api
base resource
category resource
WEB:
web
category
category-create
index
template

2021-02-08 11:33 UTC, jcosta86 approved these changes

2021-02-08 12:17 UTC, abreumatheus requested changes
Além dos comentários, ficaram faltando os testes da controller e do DAO.

2021-02-08 12:17 UTC, abreumatheus commented on requirements.txt
> +psycopg2-binary==2.8.6
Remover o psycopg2 da lista, visto que não está sendo utilizado no projeto

2021-02-08 12:17 UTC, abreumatheus commented on src/frontend/templates/category_create.html
> +        <input type="hidden" name="id" id="id">
Essa linha não é necessária, visto que não passar valor algum pro form, pois no método create não usamos o id.

2021-02-09 01:06 UTC, abreumatheus approved these changes

2021-02-09 01:06 UTC, merged